apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: rootpass
                name: secret
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                key: db
                name: myconfig
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: user
                name: secret
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: pass
                name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myimage
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 8081
    targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  rootpass: rootpass
  user: username
  pass: password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  db: database

